package com.example.demo.model;

import java.util.Date;

public class HomeAllBidding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.bidtargetmoney
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectid;
    private String projectname;


    private Double bidtargetmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.bidreview
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String bidreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.bidopenresult
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String bidopenresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.biddiscardreason
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String biddiscardreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.bidlossreason
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String bidlossreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bidding.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Date submittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.id
     *
     * @return the value of Bidding.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.id
     *
     * @param id the value for Bidding.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.bidtargetmoney
     *
     * @return the value of Bidding.bidtargetmoney
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getBidtargetmoney() {
        return bidtargetmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.bidtargetmoney
     *
     * @param bidtargetmoney the value for Bidding.bidtargetmoney
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBidtargetmoney(Double bidtargetmoney) {
        this.bidtargetmoney = bidtargetmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.bidreview
     *
     * @return the value of Bidding.bidreview
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.bidreview
     *
     * @param projectid the value for Bidding.bidreview
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.bidreview
     *
     * @param projectname the value for Bidding.bidreview
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    public String getBidreview() {
        return bidreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.bidreview
     *
     * @param bidreview the value for Bidding.bidreview
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBidreview(String bidreview) {
        this.bidreview = bidreview == null ? null : bidreview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.bidopenresult
     *
     * @return the value of Bidding.bidopenresult
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getBidopenresult() {
        return bidopenresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.bidopenresult
     *
     * @param bidopenresult the value for Bidding.bidopenresult
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBidopenresult(String bidopenresult) {
        this.bidopenresult = bidopenresult == null ? null : bidopenresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.biddiscardreason
     *
     * @return the value of Bidding.biddiscardreason
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getBiddiscardreason() {
        return biddiscardreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.biddiscardreason
     *
     * @param biddiscardreason the value for Bidding.biddiscardreason
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBiddiscardreason(String biddiscardreason) {
        this.biddiscardreason = biddiscardreason == null ? null : biddiscardreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.bidlossreason
     *
     * @return the value of Bidding.bidlossreason
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getBidlossreason() {
        return bidlossreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.bidlossreason
     *
     * @param bidlossreason the value for Bidding.bidlossreason
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBidlossreason(String bidlossreason) {
        this.bidlossreason = bidlossreason == null ? null : bidlossreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bidding.submitTime
     *
     * @return the value of Bidding.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bidding.submitTime
     *
     * @param submittime the value for Bidding.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }
}
