package com.example.demo.model;

import java.util.Date;

public class HomeAllLedger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ContractLedger.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer id;

    private String projectid;
    private String projectname;
    private int contractyear;

    private String contractdepartment;
    private String contractopdepartment;
    private String contractobject;
    private String bidoprateregion;

    private String contractid;


    private String contractid2;


    private Date contractsigndate;

    private Date constructionstartdate;

    private Date constructionenddate;

    private Double contractmoneypredict0cny;

    private Double contractmoneypredict0usd;

    private Double contractmoneypredicttotal0rmb;

    private Double contractmoneypredicttotal0usd;

    private Double contractmoneypredict1rmb;

    private Double contractmoneypredict2rmb;

    private Double contractmoneypredict3rmb;

    private Double contractmoneypredict4rmb;

    private Double contractmoneypredict5rmb;

    private Double dailycostrmb;

    private String contractsignperson;

    private String contractbelongcnooc;

    private String contractinprocess;

    private String contractsignificant;

    private String contractyearlycnooc;

    private String comments;

    private Date submittime;

    public String getProjectid(){ return projectid;}
    public void setProjectid(String projectid){ this.projectid = projectid == null ? null : projectid.trim(); }

    public String getProjectname(){ return projectname;}
    public void setProjectname(String projectname){ this.projectname = projectname == null ? null : projectname.trim(); }

    public int getContractyear(){return contractyear;}
    public void setContractyear(int contractyear){this.contractyear = contractyear;}

    public String getContractdepartment(){ return contractdepartment;}
    public void setContractdepartment(String contractdepartment){ this.contractdepartment = contractdepartment == null ? null : contractdepartment.trim(); }
    public String getContractopdepartment(){ return contractopdepartment;}
    public void setContractopdepartment(String contractopdepartment){ this.contractopdepartment = contractopdepartment == null ? null : contractopdepartment.trim(); }
    public String getContractobject(){ return contractobject;}
    public void setContractobject(String contractobject){ this.contractobject = contractobject == null ? null : contractobject.trim(); }
    public String getBidoprateregion(){ return bidoprateregion;}
    public void setBidoprateregion(String bidoprateregion){ this.bidoprateregion = bidoprateregion == null ? null : bidoprateregion.trim(); }
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.id
     *
     * @param id the value for ContractLedger.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractid
     *
     * @return the value of ContractLedger.contractid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractid
     *
     * @param contractid the value for ContractLedger.contractid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractid(String contractid) {
        this.contractid = contractid == null ? null : contractid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractid2
     *
     * @return the value of ContractLedger.contractid2
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractid2() {
        return contractid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractid2
     *
     * @param contractid2 the value for ContractLedger.contractid2
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractid2(String contractid2) {
        this.contractid2 = contractid2 == null ? null : contractid2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractsigndate
     *
     * @return the value of ContractLedger.contractsigndate
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getContractsigndate() {
        return contractsigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractsigndate
     *
     * @param contractsigndate the value for ContractLedger.contractsigndate
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractsigndate(Date contractsigndate) {
        this.contractsigndate = contractsigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.constructionstartdate
     *
     * @return the value of ContractLedger.constructionstartdate
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getConstructionstartdate() {
        return constructionstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.constructionstartdate
     *
     * @param constructionstartdate the value for ContractLedger.constructionstartdate
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setConstructionstartdate(Date constructionstartdate) {
        this.constructionstartdate = constructionstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.constructionenddate
     *
     * @return the value of ContractLedger.constructionenddate
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getConstructionenddate() {
        return constructionenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.constructionenddate
     *
     * @param constructionenddate the value for ContractLedger.constructionenddate
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setConstructionenddate(Date constructionenddate) {
        this.constructionenddate = constructionenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict0cny
     *
     * @return the value of ContractLedger.contractmoneypredict0cny
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict0cny() {
        return contractmoneypredict0cny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict0cny
     *
     * @param contractmoneypredict0cny the value for ContractLedger.contractmoneypredict0cny
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict0cny(Double contractmoneypredict0cny) {
        this.contractmoneypredict0cny = contractmoneypredict0cny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict0usd
     *
     * @return the value of ContractLedger.contractmoneypredict0usd
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict0usd() {
        return contractmoneypredict0usd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict0usd
     *
     * @param contractmoneypredict0usd the value for ContractLedger.contractmoneypredict0usd
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict0usd(Double contractmoneypredict0usd) {
        this.contractmoneypredict0usd = contractmoneypredict0usd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredicttotal0rmb
     *
     * @return the value of ContractLedger.contractmoneypredicttotal0rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredicttotal0rmb() {
        return contractmoneypredicttotal0rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredicttotal0rmb
     *
     * @param contractmoneypredicttotal0rmb the value for ContractLedger.contractmoneypredicttotal0rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredicttotal0rmb(Double contractmoneypredicttotal0rmb) {
        this.contractmoneypredicttotal0rmb = contractmoneypredicttotal0rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredicttotal0usd
     *
     * @return the value of ContractLedger.contractmoneypredicttotal0usd
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredicttotal0usd() {
        return contractmoneypredicttotal0usd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredicttotal0usd
     *
     * @param contractmoneypredicttotal0usd the value for ContractLedger.contractmoneypredicttotal0usd
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredicttotal0usd(Double contractmoneypredicttotal0usd) {
        this.contractmoneypredicttotal0usd = contractmoneypredicttotal0usd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict1rmb
     *
     * @return the value of ContractLedger.contractmoneypredict1rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict1rmb() {
        return contractmoneypredict1rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict1rmb
     *
     * @param contractmoneypredict1rmb the value for ContractLedger.contractmoneypredict1rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict1rmb(Double contractmoneypredict1rmb) {
        this.contractmoneypredict1rmb = contractmoneypredict1rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict2rmb
     *
     * @return the value of ContractLedger.contractmoneypredict2rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict2rmb() {
        return contractmoneypredict2rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict2rmb
     *
     * @param contractmoneypredict2rmb the value for ContractLedger.contractmoneypredict2rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict2rmb(Double contractmoneypredict2rmb) {
        this.contractmoneypredict2rmb = contractmoneypredict2rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict3rmb
     *
     * @return the value of ContractLedger.contractmoneypredict3rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict3rmb() {
        return contractmoneypredict3rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict3rmb
     *
     * @param contractmoneypredict3rmb the value for ContractLedger.contractmoneypredict3rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict3rmb(Double contractmoneypredict3rmb) {
        this.contractmoneypredict3rmb = contractmoneypredict3rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict4rmb
     *
     * @return the value of ContractLedger.contractmoneypredict4rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict4rmb() {
        return contractmoneypredict4rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict4rmb
     *
     * @param contractmoneypredict4rmb the value for ContractLedger.contractmoneypredict4rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict4rmb(Double contractmoneypredict4rmb) {
        this.contractmoneypredict4rmb = contractmoneypredict4rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractmoneypredict5rmb
     *
     * @return the value of ContractLedger.contractmoneypredict5rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getContractmoneypredict5rmb() {
        return contractmoneypredict5rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractmoneypredict5rmb
     *
     * @param contractmoneypredict5rmb the value for ContractLedger.contractmoneypredict5rmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractmoneypredict5rmb(Double contractmoneypredict5rmb) {
        this.contractmoneypredict5rmb = contractmoneypredict5rmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.dailycostrmb
     *
     * @return the value of ContractLedger.dailycostrmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Double getDailycostrmb() {
        return dailycostrmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.dailycostrmb
     *
     * @param dailycostrmb the value for ContractLedger.dailycostrmb
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setDailycostrmb(Double dailycostrmb) {
        this.dailycostrmb = dailycostrmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractsignperson
     *
     * @return the value of ContractLedger.contractsignperson
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractsignperson() {
        return contractsignperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractsignperson
     *
     * @param contractsignperson the value for ContractLedger.contractsignperson
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractsignperson(String contractsignperson) {
        this.contractsignperson = contractsignperson == null ? null : contractsignperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractbelongcnooc
     *
     * @return the value of ContractLedger.contractbelongcnooc
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractbelongcnooc() {
        return contractbelongcnooc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractbelongcnooc
     *
     * @param contractbelongcnooc the value for ContractLedger.contractbelongcnooc
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractbelongcnooc(String contractbelongcnooc) {
        this.contractbelongcnooc = contractbelongcnooc == null ? null : contractbelongcnooc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractinprocess
     *
     * @return the value of ContractLedger.contractinprocess
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractinprocess() {
        return contractinprocess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractinprocess
     *
     * @param contractinprocess the value for ContractLedger.contractinprocess
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractinprocess(String contractinprocess) {
        this.contractinprocess = contractinprocess == null ? null : contractinprocess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractsignificant
     *
     * @return the value of ContractLedger.contractsignificant
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractsignificant() {
        return contractsignificant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractsignificant
     *
     * @param contractsignificant the value for ContractLedger.contractsignificant
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractsignificant(String contractsignificant) {
        this.contractsignificant = contractsignificant == null ? null : contractsignificant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.contractyearlycnooc
     *
     * @return the value of ContractLedger.contractyearlycnooc
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractyearlycnooc() {
        return contractyearlycnooc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.contractyearlycnooc
     *
     * @param contractyearlycnooc the value for ContractLedger.contractyearlycnooc
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractyearlycnooc(String contractyearlycnooc) {
        this.contractyearlycnooc = contractyearlycnooc == null ? null : contractyearlycnooc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.comments
     *
     * @return the value of ContractLedger.comments
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.comments
     *
     * @param comments the value for ContractLedger.comments
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ContractLedger.submitTime
     *
     * @return the value of ContractLedger.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ContractLedger.submitTime
     *
     * @param submittime the value for ContractLedger.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }
}
