package com.example.demo.model;

import java.util.Date;

public class LedgerBase {

    private String projectid;

    private String projectname;

    private String bidregion;

    private String bidoprateregion;

    private Integer contractyear;

    private String contractdepartment;

    private String contractopdepartment;

    private String contractobject;

    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectid
     *
     * @param projectid the value for Project.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectname
     *
     * @return the value of Project.projectname
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectname
     *
     * @param projectname the value for Project.projectname
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.department
     *
     * @return the value of Project.department
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */


    public String getBidregion() {
        return bidregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidregion
     *
     * @param bidregion the value for Project.bidregion
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBidregion(String bidregion) {
        this.bidregion = bidregion == null ? null : bidregion.trim();
    }


    public String getBidoprateregion() {
        return bidoprateregion;
    }

    public void setBidoprateregion(String bidoprateregion) {
        this.bidoprateregion = bidoprateregion == null ? null : bidoprateregion.trim();
    }

    public Integer getContractyear() {
        return contractyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractyear
     *
     * @param contractyear the value for Project.contractyear
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractyear(Integer contractyear) {
        this.contractyear = contractyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractdepartment
     *
     * @return the value of Project.contractdepartment
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractdepartment() {
        return contractdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractdepartment
     *
     * @param contractdepartment the value for Project.contractdepartment
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractdepartment(String contractdepartment) {
        this.contractdepartment = contractdepartment == null ? null : contractdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractopdepartment
     *
     * @return the value of Project.contractopdepartment
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractopdepartment() {
        return contractopdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractopdepartment
     *
     * @param contractopdepartment the value for Project.contractopdepartment
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractopdepartment(String contractopdepartment) {
        this.contractopdepartment = contractopdepartment == null ? null : contractopdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractobject
     *
     * @return the value of Project.contractobject
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getContractobject() {
        return contractobject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractobject
     *
     * @param contractobject the value for Project.contractobject
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setContractobject(String contractobject) {
        this.contractobject = contractobject == null ? null : contractobject.trim();
    }
}