package com.example.demo.entity;

public class LeadFellow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LeadFellow.id
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LeadFellow.leader
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    private Integer leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LeadFellow.follew
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    private Integer follew;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LeadFellow.id
     *
     * @return the value of LeadFellow.id
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LeadFellow.id
     *
     * @param id the value for LeadFellow.id
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LeadFellow.leader
     *
     * @return the value of LeadFellow.leader
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    public Integer getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LeadFellow.leader
     *
     * @param leader the value for LeadFellow.leader
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    public void setLeader(Integer leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LeadFellow.follew
     *
     * @return the value of LeadFellow.follew
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    public Integer getFollew() {
        return follew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LeadFellow.follew
     *
     * @param follew the value for LeadFellow.follew
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    public void setFollew(Integer follew) {
        this.follew = follew;
    }
}