package com.example.demo.entity;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectid
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectname
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String projectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.department
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectgeneral
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String projectgeneral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectestimateamount
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private Double projectestimateamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectcharger
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String projectcharger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidabroad
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidabroad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidid
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidreceivedate
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private Date bidreceivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidstopdate
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private Date bidstopdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidregion
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidregion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidrecordyn
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidrecordyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidsafegrade
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidsafegrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidguaranteeyn
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidguaranteeyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidguaranteetype
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidguaranteetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidguaranteemoney
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private Double bidguaranteemoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidoperator
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidoperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidoprateregion
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidoprateregion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidservicetype
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidservicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.bidworkload
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String bidworkload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectprogress
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String projectprogress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectproblem
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String projectproblem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.contractyear
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private Integer contractyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.contractdepartment
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String contractdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.contractopdepartment
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String contractopdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.contractobject
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private String contractobject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Project.projectbuildtime
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    private Date projectbuildtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectid
     *
     * @return the value of Project.projectid
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectid
     *
     * @param projectid the value for Project.projectid
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectname
     *
     * @return the value of Project.projectname
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectname
     *
     * @param projectname the value for Project.projectname
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.department
     *
     * @return the value of Project.department
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.department
     *
     * @param department the value for Project.department
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectgeneral
     *
     * @return the value of Project.projectgeneral
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getProjectgeneral() {
        return projectgeneral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectgeneral
     *
     * @param projectgeneral the value for Project.projectgeneral
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectgeneral(String projectgeneral) {
        this.projectgeneral = projectgeneral == null ? null : projectgeneral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectestimateamount
     *
     * @return the value of Project.projectestimateamount
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public Double getProjectestimateamount() {
        return projectestimateamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectestimateamount
     *
     * @param projectestimateamount the value for Project.projectestimateamount
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectestimateamount(Double projectestimateamount) {
        this.projectestimateamount = projectestimateamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectcharger
     *
     * @return the value of Project.projectcharger
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getProjectcharger() {
        return projectcharger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectcharger
     *
     * @param projectcharger the value for Project.projectcharger
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectcharger(String projectcharger) {
        this.projectcharger = projectcharger == null ? null : projectcharger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidabroad
     *
     * @return the value of Project.bidabroad
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidabroad() {
        return bidabroad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidabroad
     *
     * @param bidabroad the value for Project.bidabroad
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidabroad(String bidabroad) {
        this.bidabroad = bidabroad == null ? null : bidabroad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidid
     *
     * @return the value of Project.bidid
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidid() {
        return bidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidid
     *
     * @param bidid the value for Project.bidid
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidid(String bidid) {
        this.bidid = bidid == null ? null : bidid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidreceivedate
     *
     * @return the value of Project.bidreceivedate
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public Date getBidreceivedate() {
        return bidreceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidreceivedate
     *
     * @param bidreceivedate the value for Project.bidreceivedate
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidreceivedate(Date bidreceivedate) {
        this.bidreceivedate = bidreceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidstopdate
     *
     * @return the value of Project.bidstopdate
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public Date getBidstopdate() {
        return bidstopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidstopdate
     *
     * @param bidstopdate the value for Project.bidstopdate
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidstopdate(Date bidstopdate) {
        this.bidstopdate = bidstopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidregion
     *
     * @return the value of Project.bidregion
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidregion() {
        return bidregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidregion
     *
     * @param bidregion the value for Project.bidregion
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidregion(String bidregion) {
        this.bidregion = bidregion == null ? null : bidregion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidrecordyn
     *
     * @return the value of Project.bidrecordyn
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidrecordyn() {
        return bidrecordyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidrecordyn
     *
     * @param bidrecordyn the value for Project.bidrecordyn
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidrecordyn(String bidrecordyn) {
        this.bidrecordyn = bidrecordyn == null ? null : bidrecordyn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidsafegrade
     *
     * @return the value of Project.bidsafegrade
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidsafegrade() {
        return bidsafegrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidsafegrade
     *
     * @param bidsafegrade the value for Project.bidsafegrade
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidsafegrade(String bidsafegrade) {
        this.bidsafegrade = bidsafegrade == null ? null : bidsafegrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidguaranteeyn
     *
     * @return the value of Project.bidguaranteeyn
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidguaranteeyn() {
        return bidguaranteeyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidguaranteeyn
     *
     * @param bidguaranteeyn the value for Project.bidguaranteeyn
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidguaranteeyn(String bidguaranteeyn) {
        this.bidguaranteeyn = bidguaranteeyn == null ? null : bidguaranteeyn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidguaranteetype
     *
     * @return the value of Project.bidguaranteetype
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidguaranteetype() {
        return bidguaranteetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidguaranteetype
     *
     * @param bidguaranteetype the value for Project.bidguaranteetype
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidguaranteetype(String bidguaranteetype) {
        this.bidguaranteetype = bidguaranteetype == null ? null : bidguaranteetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidguaranteemoney
     *
     * @return the value of Project.bidguaranteemoney
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public Double getBidguaranteemoney() {
        return bidguaranteemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidguaranteemoney
     *
     * @param bidguaranteemoney the value for Project.bidguaranteemoney
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidguaranteemoney(Double bidguaranteemoney) {
        this.bidguaranteemoney = bidguaranteemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidoperator
     *
     * @return the value of Project.bidoperator
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidoperator() {
        return bidoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidoperator
     *
     * @param bidoperator the value for Project.bidoperator
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidoperator(String bidoperator) {
        this.bidoperator = bidoperator == null ? null : bidoperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidoprateregion
     *
     * @return the value of Project.bidoprateregion
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidoprateregion() {
        return bidoprateregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidoprateregion
     *
     * @param bidoprateregion the value for Project.bidoprateregion
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidoprateregion(String bidoprateregion) {
        this.bidoprateregion = bidoprateregion == null ? null : bidoprateregion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidservicetype
     *
     * @return the value of Project.bidservicetype
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidservicetype() {
        return bidservicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidservicetype
     *
     * @param bidservicetype the value for Project.bidservicetype
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidservicetype(String bidservicetype) {
        this.bidservicetype = bidservicetype == null ? null : bidservicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.bidworkload
     *
     * @return the value of Project.bidworkload
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getBidworkload() {
        return bidworkload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.bidworkload
     *
     * @param bidworkload the value for Project.bidworkload
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setBidworkload(String bidworkload) {
        this.bidworkload = bidworkload == null ? null : bidworkload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectprogress
     *
     * @return the value of Project.projectprogress
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getProjectprogress() {
        return projectprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectprogress
     *
     * @param projectprogress the value for Project.projectprogress
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectprogress(String projectprogress) {
        this.projectprogress = projectprogress == null ? null : projectprogress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectproblem
     *
     * @return the value of Project.projectproblem
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getProjectproblem() {
        return projectproblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectproblem
     *
     * @param projectproblem the value for Project.projectproblem
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectproblem(String projectproblem) {
        this.projectproblem = projectproblem == null ? null : projectproblem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractyear
     *
     * @return the value of Project.contractyear
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public Integer getContractyear() {
        return contractyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractyear
     *
     * @param contractyear the value for Project.contractyear
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setContractyear(Integer contractyear) {
        this.contractyear = contractyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractdepartment
     *
     * @return the value of Project.contractdepartment
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getContractdepartment() {
        return contractdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractdepartment
     *
     * @param contractdepartment the value for Project.contractdepartment
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setContractdepartment(String contractdepartment) {
        this.contractdepartment = contractdepartment == null ? null : contractdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractopdepartment
     *
     * @return the value of Project.contractopdepartment
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getContractopdepartment() {
        return contractopdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractopdepartment
     *
     * @param contractopdepartment the value for Project.contractopdepartment
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setContractopdepartment(String contractopdepartment) {
        this.contractopdepartment = contractopdepartment == null ? null : contractopdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.contractobject
     *
     * @return the value of Project.contractobject
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public String getContractobject() {
        return contractobject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.contractobject
     *
     * @param contractobject the value for Project.contractobject
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setContractobject(String contractobject) {
        this.contractobject = contractobject == null ? null : contractobject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Project.projectbuildtime
     *
     * @return the value of Project.projectbuildtime
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public Date getProjectbuildtime() {
        return projectbuildtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Project.projectbuildtime
     *
     * @param projectbuildtime the value for Project.projectbuildtime
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    public void setProjectbuildtime(Date projectbuildtime) {
        this.projectbuildtime = projectbuildtime;
    }
}