package com.example.demo.entity;

public class RelationProjectBidding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RelationProjectBidding.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RelationProjectBidding.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RelationProjectBidding.biddingid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer biddingid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RelationProjectBidding.id
     *
     * @return the value of RelationProjectBidding.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RelationProjectBidding.id
     *
     * @param id the value for RelationProjectBidding.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RelationProjectBidding.projectid
     *
     * @return the value of RelationProjectBidding.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RelationProjectBidding.projectid
     *
     * @param projectid the value for RelationProjectBidding.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RelationProjectBidding.biddingid
     *
     * @return the value of RelationProjectBidding.biddingid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getBiddingid() {
        return biddingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RelationProjectBidding.biddingid
     *
     * @param biddingid the value for RelationProjectBidding.biddingid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setBiddingid(Integer biddingid) {
        this.biddingid = biddingid;
    }
}