package com.example.demo.entity;

public class RelationProjectWeekly {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RelationProjectWeekly.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RelationProjectWeekly.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RelationProjectWeekly.weeklyid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer weeklyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RelationProjectWeekly.id
     *
     * @return the value of RelationProjectWeekly.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RelationProjectWeekly.id
     *
     * @param id the value for RelationProjectWeekly.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RelationProjectWeekly.projectid
     *
     * @return the value of RelationProjectWeekly.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RelationProjectWeekly.projectid
     *
     * @param projectid the value for RelationProjectWeekly.projectid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RelationProjectWeekly.weeklyid
     *
     * @return the value of RelationProjectWeekly.weeklyid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getWeeklyid() {
        return weeklyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RelationProjectWeekly.weeklyid
     *
     * @param weeklyid the value for RelationProjectWeekly.weeklyid
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setWeeklyid(Integer weeklyid) {
        this.weeklyid = weeklyid;
    }
}