package com.example.demo.entity;

public class UserList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Userlist.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Userlist.username
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Userlist.password
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Userlist.realname
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String realname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Userlist.id
     *
     * @return the value of Userlist.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Userlist.id
     *
     * @param id the value for Userlist.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Userlist.username
     *
     * @return the value of Userlist.username
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Userlist.username
     *
     * @param username the value for Userlist.username
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Userlist.password
     *
     * @return the value of Userlist.password
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Userlist.password
     *
     * @param password the value for Userlist.password
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Userlist.realname
     *
     * @return the value of Userlist.realname
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Userlist.realname
     *
     * @param realname the value for Userlist.realname
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }
}