package com.example.demo.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.id
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.username
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.password
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.realname
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.type
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.id
     *
     * @return the value of Users.id
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.id
     *
     * @param id the value for Users.id
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.username
     *
     * @return the value of Users.username
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.username
     *
     * @param username the value for Users.username
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.password
     *
     * @return the value of Users.password
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.password
     *
     * @param password the value for Users.password
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.realname
     *
     * @return the value of Users.realname
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.realname
     *
     * @param realname the value for Users.realname
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.type
     *
     * @return the value of Users.type
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.type
     *
     * @param type the value for Users.type
     *
     * @mbg.generated Thu Oct 31 15:21:55 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}