package com.example.demo.entity;

import java.util.Date;

public class Weekly {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.projecthistory
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projecthistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.projectcurrent
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.projectstarttime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Date projectstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.projectplan
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectplan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.projectdifficulty
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectdifficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.projectsuggestion
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private String projectsuggestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Weekly.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    private Date submittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.id
     *
     * @return the value of Weekly.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.id
     *
     * @param id the value for Weekly.id
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.projecthistory
     *
     * @return the value of Weekly.projecthistory
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjecthistory() {
        return projecthistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.projecthistory
     *
     * @param projecthistory the value for Weekly.projecthistory
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjecthistory(String projecthistory) {
        this.projecthistory = projecthistory == null ? null : projecthistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.projectcurrent
     *
     * @return the value of Weekly.projectcurrent
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectcurrent() {
        return projectcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.projectcurrent
     *
     * @param projectcurrent the value for Weekly.projectcurrent
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectcurrent(String projectcurrent) {
        this.projectcurrent = projectcurrent == null ? null : projectcurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.projectstarttime
     *
     * @return the value of Weekly.projectstarttime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getProjectstarttime() {
        return projectstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.projectstarttime
     *
     * @param projectstarttime the value for Weekly.projectstarttime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectstarttime(Date projectstarttime) {
        this.projectstarttime = projectstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.projectplan
     *
     * @return the value of Weekly.projectplan
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectplan() {
        return projectplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.projectplan
     *
     * @param projectplan the value for Weekly.projectplan
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectplan(String projectplan) {
        this.projectplan = projectplan == null ? null : projectplan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.projectdifficulty
     *
     * @return the value of Weekly.projectdifficulty
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectdifficulty() {
        return projectdifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.projectdifficulty
     *
     * @param projectdifficulty the value for Weekly.projectdifficulty
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectdifficulty(String projectdifficulty) {
        this.projectdifficulty = projectdifficulty == null ? null : projectdifficulty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.projectsuggestion
     *
     * @return the value of Weekly.projectsuggestion
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public String getProjectsuggestion() {
        return projectsuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.projectsuggestion
     *
     * @param projectsuggestion the value for Weekly.projectsuggestion
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setProjectsuggestion(String projectsuggestion) {
        this.projectsuggestion = projectsuggestion == null ? null : projectsuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Weekly.submitTime
     *
     * @return the value of Weekly.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Weekly.submitTime
     *
     * @param submittime the value for Weekly.submitTime
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }
}