package com.example.demo.dao;

import com.example.demo.entity.ContractLedger;
import com.example.demo.model.HomeAllLedger;
import com.example.demo.model.LedgerSelect;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ContractLedgerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ContractLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ContractLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insert(ContractLedger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ContractLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insertSelective(ContractLedger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ContractLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    ContractLedger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ContractLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKeySelective(ContractLedger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ContractLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKey(ContractLedger record);

    List<ContractLedger> getAll();
    List<ContractLedger> getByProjectid(String id);

    List<HomeAllLedger> HomeLedgerAll(@Param("ledgerSelect") LedgerSelect ledgerSelect,@Param("list")List<Integer> list);
    List<HomeAllLedger> ProjectLedgerAll(String id);
}