package com.example.demo.dao;

import com.example.demo.controller.Param.LeadFellowArray;
import com.example.demo.controller.Param.LeaderFellowExtendUser;
import com.example.demo.entity.LeadFellow;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LeadFellowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Mon Nov 04 13:18:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Mon Nov 04 13:18:43 CST 2019
     */
    int insert(LeadFellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Mon Nov 04 13:18:43 CST 2019
     */
    int insertSelective(LeadFellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Mon Nov 04 13:18:43 CST 2019
     */
    LeadFellow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Mon Nov 04 13:18:43 CST 2019
     */
    int updateByPrimaryKeySelective(LeadFellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Mon Nov 04 13:18:43 CST 2019
     */
    int updateByPrimaryKey(LeadFellow record);

    int add(LeadFellowArray leadFellowArray);
    List<LeaderFellowExtendUser> getAllExtendUser();
    int deleteByLeaderId(@Param("id") int id);
    int deleteByFellowId(@Param("id") int id);
    List<Integer> getFellowList(@Param("id") int id);
}