package com.example.demo.dao;

import com.example.demo.entity.LeadFellow;

public interface LeadFellowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    int insert(LeadFellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    int insertSelective(LeadFellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    LeadFellow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    int updateByPrimaryKeySelective(LeadFellow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LeadFellow
     *
     * @mbg.generated Thu Oct 31 11:15:59 CST 2019
     */
    int updateByPrimaryKey(LeadFellow record);
}