package com.example.demo.dao;

import com.example.demo.entity.Project;
import com.example.demo.model.BiddingBase;
import com.example.demo.model.LedgerBase;
import com.example.demo.model.WeeklyBase;

import java.util.List;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int deleteByPrimaryKey(String projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    Project selectByPrimaryKey(String projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKey(Project record);

    List<Project> selectAll();
    WeeklyBase selectWeeklyBase(String projectid);

    BiddingBase selectBiddingBase(String projectid);

    LedgerBase selectLedgerBase(String projectid);
    String getCode();
}