package com.example.demo.dao;

import com.example.demo.entity.Project;
import com.example.demo.model.BiddingBase;
import com.example.demo.model.LedgerBase;
import com.example.demo.model.NewProjectInfo;
import com.example.demo.model.WeeklyBase;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    int deleteByPrimaryKey(String projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    Project selectByPrimaryKey(String projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 19 17:18:17 CST 2019
     */
    int updateByPrimaryKey(Project record);

    List<NewProjectInfo> getProjectInMonth(String starttime, String endtime);

    String getCode();

    LedgerBase selectLedgerBase(String projectid);

    BiddingBase selectBiddingBase(String projectid);

    WeeklyBase selectWeeklyBase(String projectid);

    List<Project> selectAll();
    String getProjectIdByProjectname(@Param("projectname")String projectname);
}