package com.example.demo.dao;

import com.example.demo.entity.Project;
import com.example.demo.model.BiddingBase;
import com.example.demo.model.LedgerBase;
import com.example.demo.model.NewProjectInfo;
import com.example.demo.model.WeeklyBase;

import java.util.List;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 26 11:24:13 CST 2019
     */
    int deleteByPrimaryKey(String projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 26 11:24:13 CST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 26 11:24:13 CST 2019
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 26 11:24:13 CST 2019
     */
    Project selectByPrimaryKey(String projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 26 11:24:13 CST 2019
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbg.generated Sat Oct 26 11:24:13 CST 2019
     */
    int updateByPrimaryKey(Project record);

    List<Project> selectAll();

    void deleteBiddingFromProject(String projectid);

    void deleteRelationProjectBiddingFromProject(String projectid);

    void deleteLedgerFromProject(String projectid);

    void deleteRelationProjectLedgerFromProject(String projectid);

    void deleteWeeklyFromProject(String projectid);

    void deleteRelationProjectWeeklyFromProject(String projectid);

    WeeklyBase selectWeeklyBase(String projectid);

    BiddingBase selectBiddingBase(String projectid);

    LedgerBase selectLedgerBase(String projectid);

    String getCode();

    List<NewProjectInfo> getProjectInMonth(String starttime, String endtime);

    String getProjectIdByProjectname(String projectname);

}