package com.example.demo.dao;

import com.example.demo.entity.RelationProjectLedger;
import org.springframework.stereotype.Repository;

@Repository
public interface RelationProjectLedgerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insert(RelationProjectLedger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insertSelective(RelationProjectLedger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    RelationProjectLedger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKeySelective(RelationProjectLedger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectLedger
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKey(RelationProjectLedger record);
    int delete(int ledgerid);
}