package com.example.demo.dao;

import com.example.demo.entity.RelationProjectBidding;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RelationProjectBiddingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectBidding
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectBidding
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insert(RelationProjectBidding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectBidding
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insertSelective(RelationProjectBidding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectBidding
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    RelationProjectBidding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectBidding
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKeySelective(RelationProjectBidding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RelationProjectBidding
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKey(RelationProjectBidding record);
    int deleteByIdProjectId(int biddingid,String projectid);
    int  getBiddingIdByProjectName(@Param("projectname") String projectname);
}