package com.example.demo.dao;

import com.example.demo.entity.UserList;

public interface UserListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Userlist
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Userlist
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insert(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Userlist
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insertSelective(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Userlist
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    UserList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Userlist
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKeySelective(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Userlist
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKey(UserList record);

    UserList selectAllByUsername(String username);
}