package com.example.demo.dao;

import com.example.demo.entity.Weekly;
import com.example.demo.model.Monthly;
import com.example.demo.model.MonthlyDownload;
import com.example.demo.model.WeeklyModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface WeeklyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Weekly
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Weekly
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insert(Weekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Weekly
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int insertSelective(Weekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Weekly
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    Weekly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Weekly
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKeySelective(Weekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Weekly
     *
     * @mbg.generated Wed Jul 17 22:42:39 CST 2019
     */
    int updateByPrimaryKey(Weekly record);

    List<Weekly> getByProjectid(String projectid);
    List<WeeklyModel> selectAll(List<Integer> list);
    List<WeeklyModel> selectAllByTime(@Param("starttime")String starttime,@Param("endtime")String endtime,@Param("list")List<Integer> list);

    List<WeeklyModel> selectWeek(List<Integer> list);
    List<WeeklyModel> selectMonth(List<Integer> list);

    int countAll(List<Integer> list);
    int countWeek(List<Integer> list);
    int countMonth(List<Integer> list);
    List<Monthly> getMonthly(List<Integer> list);
    List<MonthlyDownload> getMonthlyForDownload(@Param("starttime")String starttime,@Param("endtime")String endtime);

    List<MonthlyDownload> selectBehindTwoMonth(@Param("time")Date time, @Param("list") List<Integer> list);
    List<MonthlyDownload> selectBeforeTwoMonth(@Param("time")Date time, @Param("list") List<Integer> list);
    List<MonthlyDownload> getAboardAndSighCon(@Param("list") List<Integer> list);
}